"""create arbiter core schema

Revision ID: d43b8095396a
Revises: 
Create Date: 2026-08-31 20:55:51.639208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43b8095396a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_ledgers_merchant_id'), 'budget_ledgers', ['merchant_id'], unique=False)
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.String(length=100), nullable=False),
    sa.Column('identity_confidence', sa.Float(), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=False),
    sa.Column('history_score', sa.Float(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('behavior_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_buyer_id'), 'buyers', ['buyer_id'], unique=True)
    op.create_table('merchant_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('max_discount_pct', sa.Float(), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=False),
    sa.Column('trust_full_threshold', sa.Float(), nullable=False),
    sa.Column('trust_restricted_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_policies_merchant_id'), 'merchant_policies', ['merchant_id'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_merchant_id'), 'products', ['merchant_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('proposed_offer', sa.JSON(), nullable=False),
    sa.Column('final_offer', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('razorpay_ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_buyer_id'), 'transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_id'), 'transactions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('trust_score_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sub_scores', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trust_score_records_buyer_id'), 'trust_score_records', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_trust_score_records_session_id'), 'trust_score_records', ['session_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('trust_snapshot', sa.JSON(), nullable=False),
    sa.Column('bounds_snapshot', sa.JSON(), nullable=False),
    sa.Column('budget_snapshot', sa.JSON(), nullable=False),
    sa.Column('offer_snapshot', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reasoning_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_transaction_id'), 'audit_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_transaction_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_trust_score_records_session_id'), table_name='trust_score_records')
    op.drop_index(op.f('ix_trust_score_records_buyer_id'), table_name='trust_score_records')
    op.drop_table('trust_score_records')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_buyer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_products_merchant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_merchant_policies_merchant_id'), table_name='merchant_policies')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_buyers_buyer_id'), table_name='buyers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_budget_ledgers_merchant_id'), table_name='budget_ledgers')
    op.drop_table('budget_ledgers')
    # ### end Alembic commands ###
